name: Sample Main Push Workflow

on:
  push:
    branches:
      - main # main 브랜치로 코드가 푸시될 때 워크플로우 실행
  pull_request:
    branches:
      - main # main 브랜치에 대한 Pull Request 생성 시 워크플로우 실행

jobs:
  build:
    runs-on: ubuntu-latest # 워크플로우가 실행될 환경을 Ubuntu로 설정

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # 저장소 코드를 가져오기 위한 액션 실행

      - name: Setup JDK
        uses: actions/setup-java@v3 # JDK 환경을 설정하기 위한 액션 실행
        with:
          distribution: 'temurin' # JDK 배포판 선택
          java-version: '17' # JDK 버전을 17로 설정

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # Gradle Wrapper 스크립트에 실행 권한 부여

      - name: Build with Gradle
        run: ./gradlew build # Gradle을 사용하여 프로젝트 빌드 실행

      - name: Run Tests
        run: ./gradlew test # Gradle을 사용하여 테스트 실행

      - name: Verify Lint
        run: ./gradlew lint # Gradle을 사용하여 Lint 검사 실행
